### ISSUE TITLE
OSX not detecting the board

### ISSUE THREAD

**Issue by sjorsjes** [bruhautomation/ESP-MQTT-JSON-Multisensor#11]
When you have the same problem as I had and the board is not detected on your Mac.
Installing these drivers fixed it for me: http://www.silabs.com/Support%20Documents/Software/Mac_OSX_VCP_Driver.zip

Found the solution in: http://rossbates.com/2016/01/30/getting-started-esp8266-osx/

**Comment by bruhautomation** [comment]
Nice! Sorry about the issue, but I'm glad you got it working. Cheers!
