### ISSUE TITLE
My board not supplying 5V on VIN (floats around 2-2.2 volts)

### ISSUE THREAD

**Issue by cooljimy84** [bruhautomation/ESP-MQTT-JSON-Multisensor#25]
Easy fix, use a 3V rail, but be worth noting on the wiring image.

**Comment by bruhautomation** [comment]
What kind of power supply are you using? You should be getting the power straight from the supply on that pin. Or at least that's my understanding.

**Comment by cooljimy84** [comment]
I think its my clone board, reading more into it they might be using that pin as a battery charging pin ?!?

I'd close this, as I just wanted to note it for someone.

Also thanks for the awesome Vids, I was ready to give up with HASS, due to lots of command line editing, but it's soooooo powerful !
