### ISSUE TITLE
LDR Time Series

### ISSUE THREAD

**Issue by ntalekt** [bruhautomation/ESP-MQTT-JSON-Multisensor#29]
Anyone else having this weird time series issue? The lights were off (0 LUX) until 1:27:33PM when I turned them on for a little bit. Instead of the time series being 0 for the time period before I turned on the light there is a diagonal line. Almost like HA isn't logging the 0 data points.

![screenshot_20170708-183012](https://user-images.githubusercontent.com/6133346/27990438-228a0810-640c-11e7-930a-a6dba4cd0600.png)

**Comment by AaronLayton** [comment]
I have not had this, although, my LUX seems to be backwards - so I get a higher value when it's dark

**Comment by kernelheap** [comment]
my LUX is backwards too. If I throw the iphone flashlight on it, it indicates 80 lux. Otherwise it says 565 lux. Not sure whats wrong.

**Comment by kwinck** [comment]
HA does not update if the new value is the same as the previous value. That causes the spike. Try to append 

`force_update: true`

to the sensor definition.

https://community.home-assistant.io/t/force-update-settings-for-all-components-from-configuration-yaml/2198

**Comment by rdbahm** [comment]
@kernelheap Reverse your VCC and GND lines.

Suggest this issue be closed for this repo as it's a Home Assistant quirk, not a problem with the sensor.

**Comment by ntalekt** [comment]
@rdbahm Agreed. Thanks!
