### ISSUE TITLE
Temp going up when cooling (have changed to Celsius)

### ISSUE THREAD

**Issue by pornstrup** [bruhautomation/ESP-MQTT-JSON-Multisensor#31]
Thanks for a great multisensor-node. 

I have a problem with the temp-sensor. When blowing cool air to the sensor it gives higher values (ex. going from 25 Celsius to 35 Celsius). I have tried to switch the 3v and G wires without effect. Im using the DHT22 temp-sensor you have a link to in readme. I have no clue whats wrong.

**Comment by bachoo786** [comment]
I am having the same issues as you. Not getting the correct temperature readings shows warm temperature by 5 to 8 degrees than the current temperature. Any ideas on how to resolve this issue?
