### ISSUE TITLE
Will code work with D1 Mini V2 NodeMcu board?

### ISSUE THREAD

**Issue by DNA99** [bruhautomation/ESP-MQTT-JSON-Multisensor#32]

**Comment by DNA99** [comment]
Hi,

I would like to do this project with the D1 Mini V2 NodeMcu board. Does anyone know if the same code will work on that board?

**Comment by AaronLayton** [comment]
Hi @DNA99 

The code should be compatible as its still based off the **ESP8266** chipset. As this board has less pin outs, you would need to put it on some breadboard so you can share the GND and 3v / 5v rails

**Comment by DNA99** [comment]
Thanks Aaron!
