### ISSUE TITLE
missing define mqtt_port

### ISSUE THREAD

**Issue by hinrg** [bruhautomation/ESP-MQTT-JSON-Multisensor#4]
Hey Ben,

Latest version is missing #define mqtt_port 1883 ;)

Might also be worth adding that a fresh install of the SDK you need to install DHT sensor library and Adfruit unified sensor.

Cheers,
J

**Comment by bruhautomation** [comment]
Ah, great catch! Thanks for pointing that out. Yeah, can't believe I missed the DHT library in my video. Guess I've had that installed for so long I'd forgotten about it. I'll add a note to the code. Cheers!
