### ISSUE TITLE
Sensor Data in Serial but not in HA

### ISSUE THREAD

**Issue by ill-tempered** [bruhautomation/ESP-MQTT-JSON-Multisensor#49]
I can see the data scrolling in the serial connection but HA readings are all UNKNOWN.

topic subscribed in HA (MQTT) is correct

LED control works
  
**UPDATE: Nevermind - it was the MQTT MAX packet size parameter in PubSub Library**

**Comment by consolacion** [comment]
is your MQTT broker setup correctly? is your  device connecting to it?
Check the traffic with e.g. MQTTspy
