### ISSUE TITLE
Contast reboots 

### ISSUE THREAD

**Issue by therains** [bruhautomation/ESP-MQTT-JSON-Multisensor#61]
I have been using these sensors for the past year and have gone to flash another today and am seeing constant reboots, i tried this on two different chips any idea what the issue may be ? 

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v614f7c32
~ld
calibrating sensor Starting Node named sensornode1

Connecting to xxxxxxxxxxxxxxxxxxxxxxxx
.....
WiFi connected
IP address: 
192.168.1.105
Ready
IPess: x
Attempting MQTT connection...connected
Setting LEDs:
r: 0, g: 0, b: 0
{"state":"OFF","color":{"r":255,"g":255,"b":255},"brightness":255,"humidity":"0.00","motion":"","ldr":"0","temperature":"0.00","heatIndex":"nan"}
{"state":"OFF","color":{"r":255,"g":255,"b":255},"brightness":255,"humidity":"0.00","motion":"standby","ldr":"0","temperature":"0.00","heatIndex":"nan"}
resettin⸮
 ets Jan  8 2013,rst cause:2, boot mode:(3,2)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v614f7c32
~ld
calibrating sensor Starting Node named sensornode1

**Comment by consolacion** [comment]
often that is a psu problem. I presume you checked the other thread on the subject?

**Comment by therains** [comment]
Downgraded ide to the version the previous chips where flashed on. Same  port/cable . Resolved my issue..
