### ISSUE TITLE
MQTT not functional after Wifi disconnect

### ISSUE THREAD

**Issue by knutella** [bruhautomation/ESP-MQTT-JSON-Multisensor#8]
About once a day my sensor would just stop being able to send or receive data over MQTT.  I could still ping the MCU.  The serial monitor showed nothing.

I was able to replicate the issue either by simply rebooting my router or using the Wifi MAC filter to temporarily block the MCU.  Afterwards the MCU would reconnect to wifi (as evidenced by the ping) but no longer function for MQTT send/receive.

**Comment by TheFitzZZ** [comment]
I may experience the same issue. I have six sensors around the house and yesterday I noticed that two weren't sending updates anymore for no reason. Maybe we need some kind of automatic restart or so?

**Comment by knutella** [comment]
I wrote a fix for this issue and submitted it, its been working reliably for about a week now.

[sketch_may04a.txt](https://github.com/bruhautomation/ESP-MQTT-JSON-Multisensor/files/1004853/sketch_may04a.txt)

**Comment by bruhautomation** [comment]
Sorry about the issue! Knutella has a solid fix for this which I will merge ASAP. Thanks much for reporting it and for the fix @knutella!

**Comment by TheFitzZZ** [comment]
Can confirm that this solves this issue perfectly, have been testing it since @knutella posted the fix.

**Comment by bruhautomation** [comment]
I just merged this code into the repo so the fix should now be live. Thanks for the patch @knutella! Cheers!
